<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/panda/exts/struts2/views/action-alert.ftl"/>
		<br/>

		<#assign _columns_ = [{
			"name": "_number_",
			"type": "number",
			"nowrap": true,
			"fixed": true
		}, {
			"name": "_check_",
			"type": "check",
			"nowrap": true,
			"fixed": true
		}{
			"name": "id",
			"pkey" : true,
			"header": action.getText("bdelete-column-id", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-id-tip", "")			
		}, {
			"name": "name",
			"header": action.getText("bdelete-column-name", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-name-tip", "")			
		}] />

		<@p.listview id="samplefile_bdelete"
			action="samplefile_bdelete_execute" method="post"
			list="ds" columns=_columns_
		>
		</@p.listview>
		
		<br/>
		<div class="n-tcenter">
			<@p.submit icon="icon-bdelete-execute" onclick="return samplefile_bdelete_submit();" theme="simple"><@p.text name="button-bdelete-execute"/></@p.submit>
		<#if action.hasPermission("samplefile_list")>
			<@p.url var="_u_" action='samplefile_list'/>
			<@p.submit icon="icon-list" onclick="location.href='${_u_}';return false;" theme="simple"><@p.text name='button-list'/></@p.submit>
		</#if>

			<script type="text/javascript"><!--
				function samplefile_bdelete_submit() {
					return nlv_submitCheckedKeys('samplefile_bdelete');
				}
				
				$(function() {
					nlv_checkAll('samplefile_bdelete');
				});
			--></script>
		</div>
	</div>
</div>

</body>
</html>
