<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("samplefile_list")>
			<li><@n.a icon="icon-list" action="samplefile_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-cform" id="samplefile" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
			
			<@n.viewfield
				name="d.name"
				label="%{getText('insert-name', '')}"
			/>
			<@n.uploader
				name="d.fileField"
				disabled="${successMethodResult?string}"
				readonly="true"
				label="%{getText('insert-fileField', '')}"
			>
				<@s.param name="uploadAction"><@n.url action='fu' namespace='/images' escapeAmp='false'></@n.url></@s.param>
				<@s.param name="uploadParam">file</@s.param>
				<@s.param name="dnloadAction"><@n.url action='fd' namespace='/images' escapeAmp='false'></@n.url></@s.param>
				<@s.param name="dnloadParam">fn</@s.param>
			</@n.uploader>
			<@n.uploader
				name="d.imageField"
				disabled="${successMethodResult?string}"
				readonly="true"
				label="%{getText('insert-imageField', '')}"
			>
				<@s.param name="uploadAction"><@n.url action='iu' namespace='/images' escapeAmp='false'></@n.url></@s.param>
				<@s.param name="uploadParam">image</@s.param>
				<@s.param name="dnloadAction"><@n.url action='id' namespace='/images' escapeAmp='false'></@n.url></@s.param>
				<@s.param name="dnloadParam">fn</@s.param>
			</@n.uploader>
			<@n.submit icon="icon-insert-execute" action="samplefile_insert_execute" group="start"><@n.text name="button-insert-execute"/></@n.submit>
			<@n.submit icon="icon-back" action="samplefile_insert_input" group="end"><@n.text name="button-back"/></@n.submit>
		</@n.form>
	</div>
</div>

</body>
</html>
