<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasPermission("samplefile_list")>
			<li><@p.a icon="icon-list" action="samplefile_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-cform" id="samplefile" method="post" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('insert-name', '')}"
			/>
			<@p.uploader
				name="d.fileField"
				disabled="${successMethodResult?string}"
				readonly="true"
				label="%{getText('insert-fileField', '')}"
			>
				<@s.param name="uploadAction"><@p.url action='fu' namespace='/images' escapeAmp='false'></@p.url></@s.param>
				<@s.param name="uploadParam">file</@s.param>
				<@s.param name="dnloadAction"><@p.url action='fd' namespace='/images' escapeAmp='false'></@p.url></@s.param>
				<@s.param name="dnloadParam">fn</@s.param>
			</@p.uploader>
			<@p.uploader
				name="d.imageField"
				disabled="${successMethodResult?string}"
				readonly="true"
				label="%{getText('insert-imageField', '')}"
			>
				<@s.param name="uploadAction"><@p.url action='iu' namespace='/images' escapeAmp='false'></@p.url></@s.param>
				<@s.param name="uploadParam">image</@s.param>
				<@s.param name="dnloadAction"><@p.url action='id' namespace='/images' escapeAmp='false'></@p.url></@s.param>
				<@s.param name="dnloadParam">fn</@s.param>
			</@p.uploader>
			<@p.submit icon="icon-insert-execute" action="samplefile_insert_execute" group="start"><@p.text name="button-insert-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="samplefile_insert_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
