<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-vform" id="samplefile" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('print-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('print-name', '')}"
			/>
			<@p.uploader
				name="d.fileField"
				disabled="${successMethodResult?string}"
				readonly="true"
				label="%{getText('print-fileField', '')}"
			>
				<#if d?? && d.fileField?? && d.fileField.exist>
					<@s.param name="uploadAction"><@p.url action='fu' namespace='/images' escapeAmp='false'></@p.url></@s.param>
					<@s.param name="uploadParam">file</@s.param>
					<@s.param name="dnloadAction"><@p.url action='fd' namespace='/images' escapeAmp='false'></@p.url></@s.param>
					<@s.param name="dnloadParam">fn</@s.param>
					<@s.param name="defaultLink"><@p.url action='sf' namespace='/images' escapeAmp='false'><@s.param name="id" value="d.id"/></@p.url></@s.param>
					<@s.param name="defaultText"><@p.text name="label-attachment"/></@s.param>
				</#if>
			</@p.uploader>
			<@p.uploader
				name="d.imageField"
				disabled="${successMethodResult?string}"
				readonly="true"
				label="%{getText('print-imageField', '')}"
			>
				<#if d?? && d.imageField?? && d.imageField.exist>
					<@s.param name="uploadAction"><@p.url action='iu' namespace='/images' escapeAmp='false'></@p.url></@s.param>
					<@s.param name="uploadParam">image</@s.param>
					<@s.param name="dnloadAction"><@p.url action='id' namespace='/images' escapeAmp='false'></@p.url></@s.param>
					<@s.param name="dnloadParam">fn</@s.param>
					<@s.param name="defaultLink"><@p.url action='si' namespace='/images' escapeAmp='false'><@s.param name="id" value="d.id"/></@p.url></@s.param>
					<@s.param name="defaultText"><@p.text name="label-attachment"/></@s.param>
				</#if>
			</@p.uploader>
		</@p.form>
	</div>
</div>

</body>
</html>
