<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>
		<br/>

		<#assign _columns_ = [{
			"name": "_number_",
			"type": "number",
			"nowrap": true,
			"fixed": true
		}, {
			"name": "_check_",
			"type": "check",
			"nowrap": true,
			"fixed": true
		}{
			"name": "id",
			"pkey" : true,
			"header": action.getText("bdelete-column-id", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-id-tip", "")			
		}, {
			"name": "name",
			"header": action.getText("bdelete-column-name", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-name-tip", "")			
		}, {
			"name": "compositeUnique1",
			"header": action.getText("bdelete-column-compositeUnique1", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-compositeUnique1-tip", "")			
		}, {
			"name": "compositeUnique2",
			"header": action.getText("bdelete-column-compositeUnique2", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-compositeUnique2-tip", "")			
		}] />

		<@n.listview id="sampleunique_bdelete"
			action="sampleunique_bdelete_execute" method="post"
			list="ds" columns=_columns_ cssColumn="invalid"
		>
		</@n.listview>
		
		<br/>
		<div class="n-tcenter">
			<@n.submit icon="icon-bdelete-execute" onclick="return sampleunique_bdelete_submit();" theme="simple"><@n.text name="button-bdelete-execute"/></@n.submit>
		<#if action.hasPermission("sampleunique_list")>
			<@n.url var="_u_" action='sampleunique_list'/>
			<@n.submit icon="icon-list" onclick="location.href='${_u_}';return false;" theme="simple"><@n.text name='button-list'/></@n.submit>
		</#if>

			<script type="text/javascript"><!--
				function sampleunique_bdelete_submit() {
					return nlv_submitCheckedKeys('sampleunique_bdelete');
				}
				
				$(function() {
					nlv_checkAll('sampleunique_bdelete');
				});
			--></script>
		</div>
	</div>
</div>

</body>
</html>
