<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
			<li><@n.a icon="icon-refresh" href="javascript:location.reload(true)"><@n.text name='button-refresh'/></@n.a></li>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<#assign _columns_ = [{
			"name": "_number_",
			"type": "number",
			"header": action.getText("list-column-_number_", ""),
			"nowrap": true,
			"fixed": true
		}] />

		<#assign _actions_ = [] />
		<#assign _ash_ = "" />
		<#if action.hasPermission("sampleunique_insert")>
			<@n.url var="_u_" action="sampleunique_insert"/>
			<@n.text var="_icon_" name="icon-insert"/>
			<#assign _ash_ = "<a class=\"n-lv-ia\" href=\"" + _u_
					+ "\" title=\"" + action.getText("tooltip-insert", "")?html + "\">"/>
			<#if _icon_?has_content>
				<#assign _ash_ = _ash_ + "<img class=\"n-lv-i n-icon " + _icon_ 
					+ "\" src=\"" + static + "/nuts/images/s.gif\"></img>"/>
			</#if>
			<#assign _ash_ = _ash_ + action.getText("label-insert", "") + "</a>"/>
		</#if>
		<#if action.hasPermission("sampleunique_copy")>
			<#assign _actions_ = _actions_ + [{
				"action": "sampleunique_copy",
				"icon": action.getText("icon-copy"),
				"label": action.getText("label-copy", ""),
				"tooltip": action.getText("tooltip-copy", "")
			}] />
		</#if>
		<#if action.hasPermission("sampleunique_update")>
			<#assign _actions_ = _actions_ + [{
				"action": "sampleunique_update",
				"icon": action.getText("icon-update"),
				"label": action.getText("label-update", ""),
				"tooltip": action.getText("tooltip-update", "")
			}] />
		</#if>
		<#if action.hasPermission("sampleunique_delete")>
			<#assign _actions_ = _actions_ + [{
				"action": "sampleunique_delete",
				"icon": action.getText("icon-delete"),
				"label": action.getText("label-delete", ""),
				"tooltip": action.getText("tooltip-delete", "")
			}] />
		</#if>
		<#if _actions_?has_content || _ash_?has_content>
			<#if !(_ash_?has_content)>
				<#assign _ash_ = action.getText("list-column-_actions_", "")/>
			</#if>
			<#assign _actionc_ = [{
				"name": "_actions_",
				"type": "actions",
				"header": _ash_,
				"actions": _actions_,
				"nowrap": true,
				"fixed": true
			}] />
		</#if>
		<#if action.getText("listview-actions-align", "left") == "left">
			<#assign _columns_ = _columns_ + _actionc_![]/>
		</#if>

		<#if action.hasPermission("sampleunique_bdelete")>
			<#assign _columns_ = _columns_ + [{
				"name": "_check_",
				"type": "check",
				"nowrap": true,
				"fixed": true
			}] />
		</#if>

		<#assign _columns_ = _columns_ + [{
				"name" : "id",
				"pkey" : true,
				"header": action.getText("list-column-id"),
				"filter": {
					"type": "number"
				},
				"link": true,
				"sortable": true,
				"tooltip": action.getText("list-column-id-tip", "")
			}, {
				"name" : "name",
				"header": action.getText("list-column-name"),
				"filter": {
					"type": "string"
				},
				"sortable": true,
				"tooltip": action.getText("list-column-name-tip", "")
			}, {
				"name" : "compositeUnique1",
				"header": action.getText("list-column-compositeUnique1"),
				"filter": {
					"type": "string"
				},
				"sortable": true,
				"tooltip": action.getText("list-column-compositeUnique1-tip", "")
			}, {
				"name" : "compositeUnique2",
				"header": action.getText("list-column-compositeUnique2"),
				"filter": {
					"type": "string"
				},
				"sortable": true,
				"tooltip": action.getText("list-column-compositeUnique2-tip", "")
			}
		] />

		<#if action.getText("listview-actions-align", "") == "right">
			<#assign _columns_ = _columns_ + _actionc_![]/>
		</#if>

		<@n.listview id="sampleunique_list" action="sampleunique_list" 
			list="ds" columns=_columns_ cssColumn="invalid"
			start="pg.s" limit="pg.l" total="pg.t" sort="so.c" dir="so.d" filters="qf" filterm="qm" pager="true"
			link={ "action": "sampleunique_view", "params": { "d.id": "id" } }
		>
			<@s.param name="tools">
				<#if action.hasPermission("sampleunique_bdelete")>
					<@n.submit icon="icon-bdelete" action="sampleunique_bdelete" onclick="return sampleunique_list_bdelete();" theme="simple"><@n.text name="button-bdelete"/></@n.submit>
				</#if>
				<#if action.hasPermission("sampleunique_list_print")>
					<@n.submit icon="icon-print" onclick="return sampleunique_list_print();" theme="simple"><@n.text name="button-print"/></@n.submit>
				</#if>
				<#if action.hasPermission("sampleunique_list_csv")>
					<@n.submit icon="icon-csv" onclick="return sampleunique_list_csv();" theme="simple"><@n.text name="button-csv"/></@n.submit>
				</#if>
				<#if action.hasPermission("/json/sampleunique_list")>
					<@n.submit icon="icon-json" onclick="return sampleunique_list_json();" theme="simple"><@n.text name="button-json"/></@n.submit>
				</#if>
				<#if action.hasPermission("/xml/samplequnique_list")>
					<@n.submit icon="icon-xml" onclick="return sampleunique_list_xml();" theme="simple"><@n.text name="button-xml"/></@n.submit>
				</#if>
				<#if action.hasPermission("sampleunique_list_print")>
					<@n.submit icon="icon-pdf-list_print" onclick="return sampleunique_list_pdf_list_print();" theme="simple"><@n.text name="button-pdf-list_print"/></@n.submit>
				</#if>
			</@s.param>
		</@n.listview>

		<script type="text/javascript"><!--
			function sampleunique_list_bdelete() {
				return nlv_submitCheckedKeys('sampleunique_list', '<@n.url action="sampleunique_bdelete"/>');
			}
			function sampleunique_list_print() {
				window.open("<@n.url action='sampleunique_list_print' includeParams='all' escapeAmp='false'/>");
				return false;
			}
			function sampleunique_list_csv() {
				window.open("<@n.url action='sampleunique_list_csv' includeParams='all' escapeAmp='false'/>");
				return false;
			}
			function sampleunique_list_json() {
				window.open("<@n.url action='sampleunique_list' namespace='/json' includeParams='all' escapeAmp='false'/>");
				return false;
			}
			function sampleunique_list_xml() {
				window.open("<@n.url action='samplequnique_list' namespace='/xml' includeParams='all' escapeAmp='false'/>");
				return false;
			}
			function sampleunique_list_pdf_list_print() {
				window.open("<@n.url action='pdf' namespace='/' escapeAmp='false'/>?url=" + encodeURIComponent("<@n.url action='sampleunique_list_print' forceAddSchemeHostAndPort='true' escapeAmp='false'/>" + location.search));
				return false;
			}
		--></script>
	</div>
</div>

</body>
</html>
