<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampleunique_list")>
			<li><@n.a icon="icon-list" action="sampleunique_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-cform" id="sampleunique" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@n.viewfield
				name="d.name"
				label="%{getText('copy-name', '')}"
			/>
			
			<@n.viewfield
				name="d.compositeUnique1"
				label="%{getText('copy-compositeUnique1', '')}"
			/>
			
			<@n.viewfield
				name="d.compositeUnique2"
				label="%{getText('copy-compositeUnique2', '')}"
			/>
			<@n.submit icon="icon-copy-execute" action="sampleunique_copy_execute" group="start"><@n.text name="button-copy-execute"/></@n.submit>
			<@n.submit icon="icon-back" action="sampleunique_copy_input" group="end"><@n.text name="button-back"/></@n.submit>
		</@n.form>
	</div>
</div>

</body>
</html>
