<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-vform" id="sampleunique" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('print-id', '')}"
			/>
			
			<@n.viewfield
				name="d.name"
				label="%{getText('print-name', '')}"
			/>
			
			<@n.viewfield
				name="d.compositeUnique1"
				label="%{getText('print-compositeUnique1', '')}"
			/>
			
			<@n.viewfield
				name="d.compositeUnique2"
				label="%{getText('print-compositeUnique2', '')}"
			/>
		</@n.form>
	</div>
</div>

</body>
</html>
