<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasDataPermission(d!, "sampletags_print")>
			<li><@n.a icon="icon-print" target="_blank" action="sampletags_print"><@s.param name="d.id" value="d.id"/><@n.text name='button-print'/></@n.a></li>
		</#if>
			<li><@n.a icon="icon-pdf-print" target="_blank" action="pdf" namespace="/">				<@s.param name="url"><@n.url action='sampletags_print' forceAddSchemeHostAndPort='true' escapeAmp='false'>
						<@s.param name="d.id" value="d.id"/>
				</@n.url></@s.param><@n.text name='button-pdf-print'/></@n.a></li>
		<#if action.hasPermission("sampletags_list")>
			<li><@n.a icon="icon-list" action="sampletags_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-sform" id="sampletags" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@n.viewfield
				name="d.name"
				label="%{getText('copy-name', '')}"
			/>
			
			<@n.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('copy-boolField', '')}"
			/>
			
			<@n.viewfield
				name="d.intField"
				label="%{getText('copy-intField', '')}"
			/>
			
			<@n.viewfield
				name="d.decField"
				label="%{getText('copy-decField', '')}"
			/>
			
			<@n.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('copy-radioField', '')}"
			/>
			
			<@n.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('copy-selectField', '')}"
			/>
			
			<@n.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('copy-checkField', '')}"
			/>
			
			<@n.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('copy-datetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('copy-dateField', '')}"
			/>
			
			<@n.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('copy-timeField', '')}"
			/>
			
			<@n.viewfield
				name="d.htmlField"
				label="%{getText('copy-htmlField', '')}"
			/>
			
			<@n.viewfield
				name="d.bbcodeField"
				label="%{getText('copy-bbcodeField', '')}"
			/>
			<#assign _buttons_ = [] />
			<#if action.hasDataPermission(d!, 'sampletags_update')>
				<@n.url var="_u_" action="sampletags_update" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@n.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-update",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-update"
				}]/>
			</#if>
			<#if action.hasDataPermission(d!, 'sampletags_copy')>
				<@n.url var="_u_" action="sampletags_copy" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@n.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-copy",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-copy"
				}]/>
			</#if>
			<#if action.hasPermission('sampletags_insert')>
				<@n.url var="_u_" action="sampletags_insert"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-insert",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-insert"
				}]/>
			</#if>
			<#if action.hasDataPermission(d!, 'sampletags_delete')>
				<@n.url var="_u_" action="sampletags_delete" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@n.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-delete",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-delete"
				}]/>
			</#if>
			<#if action.hasPermission('sampletags_list')>
				<@n.url var="_u_" action="sampletags_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/nuts/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@n.form>
	</div>
</div>

</body>
</html>
