<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampletags_list")>
			<li><@n.a icon="icon-list" action="sampletags_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-sform" id="sampletags" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('delete-id', '')}"
			/>
			
			<@n.viewfield
				name="d.name"
				label="%{getText('delete-name', '')}"
			/>
			
			<@n.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('delete-boolField', '')}"
			/>
			
			<@n.viewfield
				name="d.intField"
				label="%{getText('delete-intField', '')}"
			/>
			
			<@n.viewfield
				name="d.decField"
				label="%{getText('delete-decField', '')}"
			/>
			
			<@n.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('delete-radioField', '')}"
			/>
			
			<@n.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('delete-selectField', '')}"
			/>
			
			<@n.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('delete-checkField', '')}"
			/>
			
			<@n.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('delete-datetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('delete-dateField', '')}"
			/>
			
			<@n.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('delete-timeField', '')}"
			/>
			
			<@n.viewfield
				name="d.htmlField"
				label="%{getText('delete-htmlField', '')}"
			/>
			
			<@n.viewfield
				name="d.bbcodeField"
				label="%{getText('delete-bbcodeField', '')}"
			/>
			<#assign _buttons_ = [] />
			<#if action.hasPermission('sampletags_list')>
				<@n.url var="_u_" action="sampletags_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/nuts/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@n.form>
	</div>
</div>

</body>
</html>
