<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasDataPermission(d!, "sampletags_print")>
			<li><@p.a icon="icon-print" target="_blank" action="sampletags_print"><@s.param name="d.id" value="d.id"/><@p.text name='button-print'/></@p.a></li>
		</#if>
			<li><@p.a icon="icon-pdf-print" target="_blank" action="pdf" namespace="/">				<@s.param name="url"><@p.url action='sampletags_print' forceAddSchemeHostAndPort='true' escapeAmp='false'>
						<@s.param name="d.id" value="d.id"/>
				</@p.url></@s.param><@p.text name='button-pdf-print'/></@p.a></li>
		<#if action.hasPermission("sampletags_list")>
			<li><@p.a icon="icon-list" action="sampletags_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-sform" id="sampletags" method="post" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('insert-name', '')}"
			/>
			
			<@p.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('insert-boolField', '')}"
			/>
			
			<@p.viewfield
				name="d.intField"
				label="%{getText('insert-intField', '')}"
			/>
			
			<@p.viewfield
				name="d.decField"
				label="%{getText('insert-decField', '')}"
			/>
			
			<@p.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('insert-radioField', '')}"
			/>
			
			<@p.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('insert-selectField', '')}"
			/>
			
			<@p.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('insert-checkField', '')}"
			/>
			
			<@p.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('insert-datetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('insert-dateField', '')}"
			/>
			
			<@p.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('insert-timeField', '')}"
			/>
			
			<@p.viewfield
				name="d.htmlField"
				label="%{getText('insert-htmlField', '')}"
			/>
			
			<@p.viewfield
				name="d.bbcodeField"
				label="%{getText('insert-bbcodeField', '')}"
			/>
			<#assign _buttons_ = [] />
			<#if action.hasDataPermission(d!, 'sampletags_update')>
				<@p.url var="_u_" action="sampletags_update" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@p.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-update",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-update"
				}]/>
			</#if>
			<#if action.hasDataPermission(d!, 'sampletags_copy')>
				<@p.url var="_u_" action="sampletags_copy" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@p.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-copy",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-copy"
				}]/>
			</#if>
			<#if action.hasPermission('sampletags_insert')>
				<@p.url var="_u_" action="sampletags_insert"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-insert",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-insert"
				}]/>
			</#if>
			<#if action.hasDataPermission(d!, 'sampletags_delete')>
				<@p.url var="_u_" action="sampletags_delete" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@p.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-delete",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-delete"
				}]/>
			</#if>
			<#if action.hasPermission('sampletags_list')>
				<@p.url var="_u_" action="sampletags_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>
	</div>
</div>

</body>
</html>
