<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-cform" id="sampletags" method="post" theme="nxhtml">
			<@p.viewfield
				name="d.id"
				label="%{getText('delete-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('delete-name', '')}"
			/>
			
			<@p.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('delete-boolField', '')}"
			/>
			
			<@p.viewfield
				name="d.intField"
				label="%{getText('delete-intField', '')}"
			/>
			
			<@p.viewfield
				name="d.decField"
				label="%{getText('delete-decField', '')}"
			/>
			
			<@p.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('delete-radioField', '')}"
			/>
			
			<@p.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('delete-selectField', '')}"
			/>
			
			<@p.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('delete-checkField', '')}"
			/>
			
			<@p.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('delete-datetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('delete-dateField', '')}"
			/>
			
			<@p.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('delete-timeField', '')}"
			/>
			
			<@p.viewfield
				name="d.htmlField"
				label="%{getText('delete-htmlField', '')}"
			/>
			
			<@p.viewfield
				name="d.bbcodeField"
				label="%{getText('delete-bbcodeField', '')}"
			/>
			<#assign _buttons_ = [{
				"icon": "icon-delete-execute",
				"action": "sampletags_delete_execute",
				"text": "button-delete-execute"
			}]/>
			<#if action.hasPermission('sampletags_list')>
				<@p.url var="_u_" action="sampletags_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>
	</div>
</div>

</body>
</html>
