<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasPermission("sampletags_list")>
			<li><@p.a icon="icon-list" action="sampletags_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-cform" id="sampletags" method="post" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('copy-name', '')}"
			/>
			
			<@p.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('copy-boolField', '')}"
			/>
			
			<@p.viewfield
				name="d.intField"
				label="%{getText('copy-intField', '')}"
			/>
			
			<@p.viewfield
				name="d.decField"
				label="%{getText('copy-decField', '')}"
			/>
			
			<@p.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('copy-radioField', '')}"
			/>
			
			<@p.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('copy-selectField', '')}"
			/>
			
			<@p.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('copy-checkField', '')}"
			/>
			
			<@p.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('copy-datetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('copy-dateField', '')}"
			/>
			
			<@p.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('copy-timeField', '')}"
			/>
			
			<@p.viewfield
				name="d.htmlField"
				label="%{getText('copy-htmlField', '')}"
			/>
			
			<@p.viewfield
				name="d.bbcodeField"
				label="%{getText('copy-bbcodeField', '')}"
			/>
			<@p.submit icon="icon-copy-execute" action="sampletags_copy_execute" group="start"><@p.text name="button-copy-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="sampletags_copy_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
