<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-vform" id="sampletags" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('print-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('print-name', '')}"
			/>
			
			<@p.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('print-boolField', '')}"
			/>
			
			<@p.viewfield
				name="d.intField"
				label="%{getText('print-intField', '')}"
			/>
			
			<@p.viewfield
				name="d.decField"
				label="%{getText('print-decField', '')}"
			/>
			
			<@p.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('print-radioField', '')}"
			/>
			
			<@p.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('print-selectField', '')}"
			/>
			
			<@p.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('print-checkField', '')}"
			/>
			
			<@p.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('print-datetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('print-dateField', '')}"
			/>
			
			<@p.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('print-timeField', '')}"
			/>
			
			<@p.viewfield
				name="d.htmlField"
				label="%{getText('print-htmlField', '')}"
			/>
			
			<@p.viewfield
				name="d.bbcodeField"
				label="%{getText('print-bbcodeField', '')}"
			/>
		</@p.form>
	</div>
</div>

</body>
</html>
