<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasPermission("sampletags_list")>
			<li><@p.a icon="icon-list" action="sampletags_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-eform" id="sampletags" method="post" theme="bs3">
		
			<@p.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
		
			<@p.textfield
				name="d.name"
				required="true"
				maxlength="100"
				size="60"
				label="%{getText('insert-name', '')}"
				tooltip="%{getText('insert-name-tip', '')}"
			/>
		
			<@p.checkbox
				name="d.boolField"
				label="%{getText('insert-boolField', '')}"
				tooltip="%{getText('insert-boolField-tip', '')}"
			/>
		
			<@p.textfield
				name="d.intField"
				maxlength="14"
				size="16"
				label="%{getText('insert-intField', '')}"
				tooltip="%{getText('insert-intField-tip', '')}"
			/>
		
			<@p.textfield
				name="d.decField"
				maxlength="10"
				size="60"
				label="%{getText('insert-decField', '')}"
				tooltip="%{getText('insert-decField-tip', '')}"
			/>
		
			<@p.radio
				name="d.radioField"
				emptyOption="true"
				list="consts.radioMap"
				label="%{getText('insert-radioField', '')}"
				tooltip="%{getText('insert-radioField-tip', '')}"
			/>
		
			<@p.select
				name="d.selectField"
				emptyOption="true"
				list="consts.selectMap"
				label="%{getText('insert-selectField', '')}"
				tooltip="%{getText('insert-selectField-tip', '')}"
			/>
		
			<@p.checkboxlist
				name="d.checkField"
				emptyOption="true"
				list="consts.checkMap"
				label="%{getText('insert-checkField', '')}"
				tooltip="%{getText('insert-checkField-tip', '')}"
			/>
		
			<@p.datetimepicker
				name="d.datetimeField"
				format="datetime"
				maxlength="20"
				size="25"
				label="%{getText('insert-datetimeField', '')}"
				tooltip="%{getText('insert-datetimeField-tip', '')}"
			/>
		
			<@p.datepicker
				name="d.dateField"
				format="date"
				maxlength="10"
				size="15"
				label="%{getText('insert-dateField', '')}"
				tooltip="%{getText('insert-dateField-tip', '')}"
			/>
		
			<@p.timepicker
				name="d.timeField"
				format="time"
				maxlength="8"
				size="15"
				label="%{getText('insert-timeField', '')}"
				tooltip="%{getText('insert-timeField-tip', '')}"
			/>
		
			<@p.textarea
				name="d.htmlField"
				maxlength="4000"
				cols="60"
				rows="15"
				layout="html"
				label="%{getText('insert-htmlField', '')}"
				tooltip="%{getText('insert-htmlField-tip', '')}"
			/>
		
			<@p.textarea
				name="d.bbcodeField"
				maxlength="4000"
				cols="60"
				rows="15"
				layout="bbcode"
				label="%{getText('insert-bbcodeField', '')}"
				tooltip="%{getText('insert-bbcodeField-tip', '')}"
			/>
			<#assign _buttons_ = [] />
		<#if action.getTextAsBoolean('ui-input-confirm', false)>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-insert-confirm",
				"action": "sampletags_insert_confirm",
				"text": "button-insert-confirm"
			}]/>
		<#else>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-insert-execute",
				"action": "sampletags_insert_execute",
				"text": "button-insert-execute"
			}]/>
		</#if>
			<#if action.hasPermission('sampletags_list')>
				<@p.url var="_u_" action="sampletags_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>

		<script type="text/javascript"><!--
		--></script>
	</div>
</div>

</body>
</html>
