<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<#if action.hasErrors()>
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt-all.ftl"/>
	</div>
</div>

</body>
</html>
<#else>
<@n.text var="_fn_" name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text>
<@n.head charset="UTF-8" bom="true" contentType="text/comma-separated-values"
	noCache="true" attachment="true" filename="%{#_fn_ + '.csv'}"/>
<#assign _columns_ = [{
	"name": "id",
	"header": action.getText("list_csv-column-id"), 
	"hidden": false
}, {
	"name": "styleField",
	"header": action.getText("list_csv-column-styleField"), 
	"format": {
		"codemap": "consts.styleMap",
		"type": "code"
	},
	"hidden": false
}, {
	"name": "name",
	"header": action.getText("list_csv-column-name"), 
	"hidden": false
}, {
	"name": "boolField",
	"header": action.getText("list_csv-column-boolField"), 
	"format": {
		"type": "check"
	},
	"hidden": false
}, {
	"name": "intField",
	"header": action.getText("list_csv-column-intField"), 
	"hidden": false
}, {
	"name": "decField",
	"header": action.getText("list_csv-column-decField"), 
	"hidden": false
}, {
	"name": "radioField",
	"header": action.getText("list_csv-column-radioField"), 
	"format": {
		"codemap": "consts.radioMap",
		"type": "code"
	},
	"hidden": false
}, {
	"name": "selectField",
	"header": action.getText("list_csv-column-selectField"), 
	"format": {
		"codemap": "consts.selectMap",
		"type": "code"
	},
	"hidden": false
}, {
	"name": "checkField",
	"header": action.getText("list_csv-column-checkField"), 
	"format": {
		"codemap": "consts.checkMap",
		"type": "code"
	},
	"hidden": false
}, {
	"name": "datetimeField",
	"header": action.getText("list_csv-column-datetimeField"), 
	"format": {
		"type": "datetime"
	},
	"hidden": false
}, {
	"name": "dateField",
	"header": action.getText("list_csv-column-dateField"), 
	"format": {
		"type": "date"
	},
	"hidden": false
}, {
	"name": "timeField",
	"header": action.getText("list_csv-column-timeField"), 
	"format": {
		"type": "time"
	},
	"hidden": false
}] />
<@n.csv list="ds" columns=_columns_/>
</#if>