<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasDataPermission(d!, "samplejoin_print")>
			<li><@n.a icon="icon-print" target="_blank" action="samplejoin_print"><@s.param name="d.id" value="d.id"/><@n.text name='button-print'/></@n.a></li>
		</#if>
			<li><@n.a icon="icon-pdf-print" target="_blank" action="pdf" namespace="/">				<@s.param name="url"><@n.url action='samplejoin_print' forceAddSchemeHostAndPort='true' escapeAmp='false'>
						<@s.param name="d.id" value="d.id"/>
				</@n.url></@s.param><@n.text name='button-pdf-print'/></@n.a></li>
		<#if action.hasPermission("samplejoin_list")>
			<li><@n.a icon="icon-list" action="samplejoin_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-sform" id="samplejoin" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@n.viewfield
				name="d.tagsId"
				label="%{getText('copy-tagsId', '')}"
			/>
			<@n.viewfield
				name="d.tagsName"
				label="%{getText('copy-tagsName', '')}"
			/>
			
			<@n.viewfield
				name="d.fileId"
				label="%{getText('copy-fileId', '')}"
			/>
			<@n.viewfield
				name="d.fileName"
				label="%{getText('copy-fileName', '')}"
			/>
			<#assign _buttons_ = [] />
			<#if action.hasDataPermission(d!, 'samplejoin_update')>
				<@n.url var="_u_" action="samplejoin_update" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@n.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-update",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-update"
				}]/>
			</#if>
			<#if action.hasDataPermission(d!, 'samplejoin_copy')>
				<@n.url var="_u_" action="samplejoin_copy" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@n.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-copy",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-copy"
				}]/>
			</#if>
			<#if action.hasPermission('samplejoin_insert')>
				<@n.url var="_u_" action="samplejoin_insert"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-insert",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-insert"
				}]/>
			</#if>
			<#if action.hasDataPermission(d!, 'samplejoin_delete')>
				<@n.url var="_u_" action="samplejoin_delete" escapeAmp="false">
					<@s.param name="d.id" value="d.id"/>
				</@n.url>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-delete",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-delete"
				}]/>
			</#if>
			<#if action.hasPermission('samplejoin_list')>
				<@n.url var="_u_" action="samplejoin_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/nuts/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@n.form>
	</div>
</div>

</body>
</html>
