sudo: false
language: java
jdk:
- openjdk8

git:
  depth: 1

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/google-cloud-sdk"

services:
- docker

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
    #ENCRYPT YOUR PRIVATE KEY (If you need authentication)
    # 1. Install and login to the Travis CLI:
    #       $ gem install travis
    #       $ travis login
    # 2. Move your json private key to client-secret.json
    # 3. Run:
    #       $ travis encrypt-file client-secret.json --add
    # 4. Commit changes:
    #       $ git add client-secret.json.enc
    #       $ git commit client-secret.json.enc .travis.yml
- openssl aes-256-cbc -K $encrypted_4c66a758dd0a_key -iv $encrypted_4c66a758dd0a_iv
  -in gae/client-secret.json.enc -out gae/client-secret.json -d

install: true

before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml

script: bash .travis.build.sh
