<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("samplejoin_list")>
			<li><@p.a icon="icon-list" action="samplejoin_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-cform" id="samplejoin" method="post" theme="nxhtml">
			<@p.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@p.viewfield
				name="d.tagsId"
				label="%{getText('copy-tagsId', '')}"
			/>
			<@p.viewfield
				name="d.tagsName"
				label="%{getText('copy-tagsName', '')}"
			/>
			
			<@p.viewfield
				name="d.fileId"
				label="%{getText('copy-fileId', '')}"
			/>
			<@p.viewfield
				name="d.fileName"
				label="%{getText('copy-fileName', '')}"
			/>
			<@p.submit icon="icon-copy-execute" action="samplejoin_copy_execute" group="start"><@p.text name="button-copy-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="samplejoin_copy_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
