<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasDataPermission(d!, "samplejoin_print")>
			<li><@n.a icon="icon-print" target="_blank" action="samplejoin_print"><@s.param name="d.id" value="d.id"/><@n.text name='button-print'/></@n.a></li>
		</#if>
			<li><@n.a icon="icon-pdf-print" target="_blank" action="pdf" namespace="/">				<@s.param name="url"><@n.url action='samplejoin_print' forceAddSchemeHostAndPort='true' escapeAmp='false'>
						<@s.param name="d.id" value="d.id"/>
				</@n.url></@s.param><@n.text name='button-pdf-print'/></@n.a></li>
		<#if action.hasPermission("samplejoin_list")>
			<li><@n.a icon="icon-list" action="samplejoin_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-sform" id="samplejoin" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('delete-id', '')}"
			/>
			
			<@n.viewfield
				name="d.tagsId"
				label="%{getText('delete-tagsId', '')}"
			/>
			<@n.viewfield
				name="d.tagsName"
				label="%{getText('delete-tagsName', '')}"
			/>
			
			<@n.viewfield
				name="d.fileId"
				label="%{getText('delete-fileId', '')}"
			/>
			<@n.viewfield
				name="d.fileName"
				label="%{getText('delete-fileName', '')}"
			/>
			<#assign _buttons_ = [] />
			<#if action.hasPermission('samplejoin_list')>
				<@n.url var="_u_" action="samplejoin_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/nuts/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@n.form>
	</div>
</div>

</body>
</html>
