<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("samplejoin_list")>
			<li><@n.a icon="icon-list" action="samplejoin_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-cform" id="samplejoin" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('delete-id', '')}"
			/>
			
			<@n.viewfield
				name="d.tagsId"
				label="%{getText('delete-tagsId', '')}"
			/>
			<@n.viewfield
				name="d.tagsName"
				label="%{getText('delete-tagsName', '')}"
			/>
			
			<@n.viewfield
				name="d.fileId"
				label="%{getText('delete-fileId', '')}"
			/>
			<@n.viewfield
				name="d.fileName"
				label="%{getText('delete-fileName', '')}"
			/>
			<#assign _buttons_ = [{
				"icon": "icon-delete-execute",
				"action": "samplejoin_delete_execute",
				"text": "button-delete-execute"
			}]/>
			<#if action.hasPermission('samplejoin_list')>
				<@n.url var="_u_" action="samplejoin_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/nuts/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@n.form>
	</div>
</div>

</body>
</html>
