<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("samplejoin_list")>
			<li><@p.a icon="icon-list" action="samplejoin_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-eform" id="samplejoin" method="post" theme="nxhtml">
		
			<@p.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
		
			<@p.triggerfield
				name="d.tagsId"
				required="true"
				maxlength="28"
				size="30"
				label="%{getText('insert-tagsId', '')}"
				tooltip="%{getText('insert-tagsId-tip', '')}"
			/>
		
			<@p.viewfield
				name="d.tagsName"
				label="%{getText('insert-tagsName', '')}"
			/>
		
			<@p.triggerfield
				name="d.fileId"
				required="true"
				maxlength="28"
				size="30"
				label="%{getText('insert-fileId', '')}"
				tooltip="%{getText('insert-fileId-tip', '')}"
			/>
		
			<@p.viewfield
				name="d.fileName"
				label="%{getText('insert-fileName', '')}"
			/>
			<#assign _buttons_ = [] />
		<#if action.getTextAsBoolean('ui-input-confirm', false)>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-insert-confirm",
				"action": "samplejoin_insert_confirm",
				"text": "button-insert-confirm"
			}]/>
		<#else>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-insert-execute",
				"action": "samplejoin_insert_execute",
				"text": "button-insert-execute"
			}]/>
		</#if>
			<#if action.hasPermission('samplejoin_list')>
				<@p.url var="_u_" action="samplejoin_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>

		<script type="text/javascript"><!--
			function samplejoin_tagsId_onPopupCallback(sd) {
				$("#samplejoin_d_tagsId").val(sd.id);
				nuts.viewfield("#samplejoin_d_tagsName").val(sd.name);
				$.popup().hide();
			}
		
			$(function() {
				$.popup({
					id: "popup_samplejoin_d_tagsId",
					url: "<@p.url action="sampletags_list_popup" escapeAmp="false"></@p.url>"
				});
				
				$('#samplejoin_d_tagsId').next().popup({
					id: "popup_samplejoin_d_tagsId",
					target: "#samplejoin_d_tagsId",
					callback: samplejoin_tagsId_onPopupCallback
				});
			});
			
			function samplejoin_fileId_onPopupCallback(sd) {
				$("#samplejoin_d_fileId").val(sd.id);
				nuts.viewfield("#samplejoin_d_fileName").val(sd.name);
				$.popup().hide();
			}
		
			$(function() {
				$.popup({
					id: "popup_samplejoin_d_fileId",
					url: "<@p.url action="samplefile_list_popup" escapeAmp="false"></@p.url>"
				});
				
				$('#samplejoin_d_fileId').next().popup({
					id: "popup_samplejoin_d_fileId",
					target: "#samplejoin_d_fileId",
					callback: samplejoin_fileId_onPopupCallback
				});
			});
			
		--></script>
	</div>
</div>

</body>
</html>
