<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasPermission("samplejoin_list")>
			<li><@p.a icon="icon-list" action="samplejoin_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-cform" id="samplejoin" method="post" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('update-id', '')}"
			/>
			
			<@p.viewfield
				name="d.tagsId"
				label="%{getText('update-tagsId', '')}"
			/>
			<@p.viewfield
				name="d.tagsName"
				label="%{getText('update-tagsName', '')}"
			/>
			
			<@p.viewfield
				name="d.fileId"
				label="%{getText('update-fileId', '')}"
			/>
			<@p.viewfield
				name="d.fileName"
				label="%{getText('update-fileName', '')}"
			/>
			<@p.submit icon="icon-update-execute" action="samplejoin_update_execute" group="start"><@p.text name="button-update-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="samplejoin_update_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
