<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasPermission("sampleunique_list")>
			<li><@p.a icon="icon-list" action="sampleunique_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-eform" id="sampleunique" method="post" theme="bs3">
		
			<@p.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
		
			<@p.textfield
				name="d.name"
				required="true"
				maxlength="100"
				size="60"
				label="%{getText('copy-name', '')}"
				tooltip="%{getText('copy-name-tip', '')}"
			/>
		
			<@p.textfield
				name="d.compositeUnique1"
				required="true"
				maxlength="10"
				size="60"
				label="%{getText('copy-compositeUnique1', '')}"
				tooltip="%{getText('copy-compositeUnique1-tip', '')}"
			/>
		
			<@p.textfield
				name="d.compositeUnique2"
				required="true"
				maxlength="10"
				size="60"
				label="%{getText('copy-compositeUnique2', '')}"
				tooltip="%{getText('copy-compositeUnique2-tip', '')}"
			/>
			<#assign _buttons_ = [] />
		<#if action.getTextAsBoolean('ui-input-confirm', false)>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-copy-confirm",
				"action": "sampleunique_copy_confirm",
				"text": "button-copy-confirm"
			}]/>
		<#else>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-copy-execute",
				"action": "sampleunique_copy_execute",
				"text": "button-copy-execute"
			}]/>
		</#if>
			<#if action.hasPermission('sampleunique_list')>
				<@p.url var="_u_" action="sampleunique_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>

		<script type="text/javascript"><!--
		--></script>
	</div>
</div>

</body>
</html>
