<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<ul class="p-toolbar">
		<#if action.hasPermission("sampleunique_list")>
			<li><@p.a icon="icon-list" action="sampleunique_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-cform" id="sampleunique" method="post" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('insert-name', '')}"
			/>
			
			<@p.viewfield
				name="d.compositeUnique1"
				label="%{getText('insert-compositeUnique1', '')}"
			/>
			
			<@p.viewfield
				name="d.compositeUnique2"
				label="%{getText('insert-compositeUnique2', '')}"
			/>
			<@p.submit icon="icon-insert-execute" action="sampleunique_insert_execute" group="start"><@p.text name="button-insert-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="sampleunique_insert_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
