<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampleunique_list")>
			<li><@p.a icon="icon-list" action="sampleunique_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-cform" id="sampleunique" method="post" theme="nxhtml">
			<@p.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@p.viewfield
				name="d.name"
				label="%{getText('copy-name', '')}"
			/>
			
			<@p.viewfield
				name="d.compositeUnique1"
				label="%{getText('copy-compositeUnique1', '')}"
			/>
			
			<@p.viewfield
				name="d.compositeUnique2"
				label="%{getText('copy-compositeUnique2', '')}"
			/>
			<@p.submit icon="icon-copy-execute" action="sampleunique_copy_execute" group="start"><@p.text name="button-copy-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="sampleunique_copy_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
