<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-vform" id="sampledate" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('print-id', '')}"
			/>
			
			<@n.viewfield
				name="d.popupDatetimeField"
				format="datetime"
				label="%{getText('print-popupDatetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.popupDateField"
				format="date"
				label="%{getText('print-popupDateField', '')}"
			/>
			
			<@n.viewfield
				name="d.popupTimeField"
				format="time"
				label="%{getText('print-popupTimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.inlineDatetimeField"
				format="datetime"
				label="%{getText('print-inlineDatetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.inlineDateField"
				format="date"
				label="%{getText('print-inlineDateField', '')}"
			/>
			
			<@n.viewfield
				name="d.inlineTimeField"
				format="time"
				label="%{getText('print-inlineTimeField', '')}"
			/>
		</@n.form>
	</div>
</div>

</body>
</html>
