<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampledate_list")>
			<li><@n.a icon="icon-list" action="sampledate_list"><@n.text name='button-list'/></@n.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-cform" id="sampledate" method="post" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('copy-id', '')}"
			/>
			
			<@n.viewfield
				name="d.popupDatetimeField"
				format="datetime"
				label="%{getText('copy-popupDatetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.popupDateField"
				format="date"
				label="%{getText('copy-popupDateField', '')}"
			/>
			
			<@n.viewfield
				name="d.popupTimeField"
				format="time"
				label="%{getText('copy-popupTimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.inlineDatetimeField"
				format="datetime"
				label="%{getText('copy-inlineDatetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.inlineDateField"
				format="date"
				label="%{getText('copy-inlineDateField', '')}"
			/>
			
			<@n.viewfield
				name="d.inlineTimeField"
				format="time"
				label="%{getText('copy-inlineTimeField', '')}"
			/>
			<@n.submit icon="icon-copy-execute" action="sampledate_copy_execute" group="start"><@n.text name="button-copy-execute"/></@n.submit>
			<@n.submit icon="icon-back" action="sampledate_copy_input" group="end"><@n.text name="button-back"/></@n.submit>
		</@n.form>
	</div>
</div>

</body>
</html>
