<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
			<li><@n.a icon="icon-refresh" href="javascript:location.reload(true)"><@n.text name='button-refresh'/></@n.a></li>
		</ul>
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>
		<br/>
		
		<#assign _columns_ = [{
			"name": "_number_",
			"type": "number",
			"nowrap": true,
			"fixed": true
		}, {
			"name": "id",
			"header": action.getText("bdelete-column-id", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-id-tip", ""),
			"value": false		
		}, {
			"name": "name",
			"header": action.getText("bdelete-column-name", ""), 
			"sortable": false,
			"tooltip": action.getText("bdelete-column-name-tip", ""),
			"value": false		
		}] />

		<@n.listview id="samplefile_bdelete"
			list="ds" columns=_columns_
		>
		</@n.listview>
		
		<br/>
		<div class="n-tcenter">
		<#if action.hasPermission("samplefile_list")>
			<@n.url var="_u_" action='samplefile_list'/>
			<@n.submit icon="icon-list" onclick="location.href='${_u_}';return false;" theme="simple"><@n.text name='button-list'/></@n.submit>
		</#if>
		</div>
	</div>
</div>

</body>
</html>
