<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<h3 class="n-sect-title"><@n.text name="title-${actionResult}"><@s.param><@n.text name="title"/></@s.param></@n.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/nuts/exts/struts2/views/action-prompt.ftl"/>

		<@n.form cssClass="n-vform" id="sampletags" theme="nxhtml">
			<@n.viewfield
				name="d.id"
				label="%{getText('print-id', '')}"
			/>
			
			<@n.viewfield
				name="d.name"
				label="%{getText('print-name', '')}"
			/>
			
			<@n.viewfield
				name="d.boolField"
				format="check"
				label="%{getText('print-boolField', '')}"
			/>
			
			<@n.viewfield
				name="d.intField"
				label="%{getText('print-intField', '')}"
			/>
			
			<@n.viewfield
				name="d.decField"
				label="%{getText('print-decField', '')}"
			/>
			
			<@n.viewfield
				name="d.radioField"
				list="consts.radioMap"
				label="%{getText('print-radioField', '')}"
			/>
			
			<@n.viewfield
				name="d.selectField"
				list="consts.selectMap"
				label="%{getText('print-selectField', '')}"
			/>
			
			<@n.viewfield
				name="d.checkField"
				list="consts.checkMap"
				label="%{getText('print-checkField', '')}"
			/>
			
			<@n.viewfield
				name="d.datetimeField"
				format="datetime"
				label="%{getText('print-datetimeField', '')}"
			/>
			
			<@n.viewfield
				name="d.dateField"
				format="date"
				label="%{getText('print-dateField', '')}"
			/>
			
			<@n.viewfield
				name="d.timeField"
				format="time"
				label="%{getText('print-timeField', '')}"
			/>
			
			<@n.viewfield
				name="d.htmlField"
				label="%{getText('print-htmlField', '')}"
			/>
			
			<@n.viewfield
				name="d.bbcodeField"
				label="%{getText('print-bbcodeField', '')}"
			/>
		</@n.form>
	</div>
</div>

</body>
</html>
