name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    env:
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      AZURE_REGION: ${{ vars.AZURE_REGION }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_APPNAME: ${{ vars.AZURE_APPNAME }}
    steps:
      - name: Setup
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.352+8'
          distribution: 'adopt'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run:  cd azure && ./build.sh
