<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampledate_list")>
			<li><@p.a icon="icon-list" action="sampledate_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-cform" id="sampledate" method="post" theme="nxhtml">
			<@p.viewfield
				name="d.id"
				label="%{getText('insert-id', '')}"
			/>
			
			<@p.viewfield
				name="d.popupDatetimeField"
				format="datetime"
				label="%{getText('insert-popupDatetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.popupDateField"
				format="date"
				label="%{getText('insert-popupDateField', '')}"
			/>
			
			<@p.viewfield
				name="d.popupTimeField"
				format="time"
				label="%{getText('insert-popupTimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineDatetimeField"
				format="datetime"
				label="%{getText('insert-inlineDatetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineDateField"
				format="date"
				label="%{getText('insert-inlineDateField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineTimeField"
				format="time"
				label="%{getText('insert-inlineTimeField', '')}"
			/>
			<@p.submit icon="icon-insert-execute" action="sampledate_insert_execute" group="start"><@p.text name="button-insert-execute"/></@p.submit>
			<@p.submit icon="icon-back" action="sampledate_insert_input" group="end"><@p.text name="button-back"/></@p.submit>
		</@p.form>
	</div>
</div>

</body>
</html>
