<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampledate_list")>
			<li><@p.a icon="icon-list" action="sampledate_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">

		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-eform" id="sampledate" method="post" theme="nxhtml">
		
			<@p.viewfield
				name="d.id"
				label="%{getText('update-id', '')}"
				required="true"
			/>
		
			<@p.datetimepicker
				name="d.popupDatetimeField"
				format="datetime"
				maxlength="20"
				size="25"
				label="%{getText('update-popupDatetimeField', '')}"
				tooltip="%{getText('update-popupDatetimeField-tip', '')}"
			/>
		
			<@p.datepicker
				name="d.popupDateField"
				format="date"
				maxlength="10"
				size="15"
				label="%{getText('update-popupDateField', '')}"
				tooltip="%{getText('update-popupDateField-tip', '')}"
			/>
		
			<@p.timepicker
				name="d.popupTimeField"
				format="time"
				maxlength="8"
				size="15"
				label="%{getText('update-popupTimeField', '')}"
				tooltip="%{getText('update-popupTimeField-tip', '')}"
			/>
		
			<@p.datetimepicker
				name="d.inlineDatetimeField"
				format="datetime"
				maxlength="20"
				size="25"
				inline="true"
				label="%{getText('update-inlineDatetimeField', '')}"
				tooltip="%{getText('update-inlineDatetimeField-tip', '')}"
			/>
		
			<@p.datepicker
				name="d.inlineDateField"
				format="date"
				maxlength="10"
				size="15"
				inline="true"
				label="%{getText('update-inlineDateField', '')}"
				tooltip="%{getText('update-inlineDateField-tip', '')}"
			/>
		
			<@p.timepicker
				name="d.inlineTimeField"
				format="time"
				maxlength="8"
				size="15"
				inline="true"
				label="%{getText('update-inlineTimeField', '')}"
				tooltip="%{getText('update-inlineTimeField-tip', '')}"
			/>
			<#assign _buttons_ = [] />
		<#if action.getTextAsBoolean('ui-input-confirm', false)>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-update-confirm",
				"action": "sampledate_update_confirm",
				"text": "button-update-confirm"
			}]/>
		<#else>
			<#assign _buttons_ = _buttons_ + [{
				"icon": "icon-update-execute",
				"action": "sampledate_update_execute",
				"text": "button-update-execute"
			}]/>
		</#if>
			<#if action.hasPermission('sampledate_list')>
				<@p.url var="_u_" action="sampledate_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>

		<script type="text/javascript"><!--
		--></script>
	</div>
</div>

</body>
</html>
