<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="p-section">
	<div class="p-header">
		<h3 class="p-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/panda/exts/struts2/views/action-alert.ftl"/>

		<@p.form cssClass="n-vform" id="sampledate" theme="bs3">
			<@p.viewfield
				name="d.id"
				label="%{getText('print-id', '')}"
			/>
			
			<@p.viewfield
				name="d.popupDatetimeField"
				format="datetime"
				label="%{getText('print-popupDatetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.popupDateField"
				format="date"
				label="%{getText('print-popupDateField', '')}"
			/>
			
			<@p.viewfield
				name="d.popupTimeField"
				format="time"
				label="%{getText('print-popupTimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineDatetimeField"
				format="datetime"
				label="%{getText('print-inlineDatetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineDateField"
				format="date"
				label="%{getText('print-inlineDateField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineTimeField"
				format="time"
				label="%{getText('print-inlineTimeField', '')}"
			/>
		</@p.form>
	</div>
</div>

</body>
</html>
