<#-- This file was auto-generated by nuts.tools.codegen.FreemarkerGenerator  -->
<html>
<head>
	<title><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></title>
</head>
<body>

<div class="n-sect">
	<div class="n-sect-head">
		<ul class="n-toolbar">
		<#if action.hasPermission("sampledate_list")>
			<li><@p.a icon="icon-list" action="sampledate_list"><@p.text name='button-list'/></@p.a></li>
		</#if>
		</ul>
		<h3 class="n-sect-title"><@p.text name="title-${actionResult}"><@s.param><@p.text name="title"/></@s.param></@p.text></h3>
	</div>
	<div class="n-sect-body">
		<#include "/panda/exts/struts2/views/action-prompt.ftl"/>

		<@p.form cssClass="n-cform" id="sampledate" method="post" theme="nxhtml">
			<@p.viewfield
				name="d.id"
				label="%{getText('delete-id', '')}"
			/>
			
			<@p.viewfield
				name="d.popupDatetimeField"
				format="datetime"
				label="%{getText('delete-popupDatetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.popupDateField"
				format="date"
				label="%{getText('delete-popupDateField', '')}"
			/>
			
			<@p.viewfield
				name="d.popupTimeField"
				format="time"
				label="%{getText('delete-popupTimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineDatetimeField"
				format="datetime"
				label="%{getText('delete-inlineDatetimeField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineDateField"
				format="date"
				label="%{getText('delete-inlineDateField', '')}"
			/>
			
			<@p.viewfield
				name="d.inlineTimeField"
				format="time"
				label="%{getText('delete-inlineTimeField', '')}"
			/>
			<#assign _buttons_ = [{
				"icon": "icon-delete-execute",
				"action": "sampledate_delete_execute",
				"text": "button-delete-execute"
			}]/>
			<#if action.hasPermission('sampledate_list')>
				<@p.url var="_u_" action="sampledate_list"/>
				<#assign _buttons_ = _buttons_ + [{
					"icon": "icon-list",
					"onclick": "location.href='${_u_?js_string}'; return false;",
					"text": "button-list"
				}]/>
			</#if>
			<#include "/panda/exts/struts2/views/form-buttons.ftl"/>
			<@form_buttons buttons=_buttons_/>
		</@p.form>
	</div>
</div>

</body>
</html>
